spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path=classpath: /templates
    suffix: .ftl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poker?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r




